services:
  db:
    build: db
    restart: always
    networks:
      - backnet
    expose:
      - 1433
    ports:
      - 1433:1433
    env_file:
      - password.env


  flask_app:
    build: flask_app
    restart: always
    expose:
      - 5000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - password.env


networks:
  backnet:
    external: true
  frontnet:
    external: true