services:
  db:
    build: db
    restart: always
    networks:
      - backnet
    expose:
      - 1433

  flask:
    build: flask
    restart: always
    secrets:
      - db-password
    expose:
      - 5000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

networks:
  backnet:
    external: true
  frontnet:
    external: true