INSERT INTO RoomTypes (Room_Type_ID, Room_Cost, Room_Type)
VALUES ('1', '200', 'Standard Twin')
INSERT INTO RoomTypes (Room_Type_ID, Room_Cost, Room_Type)
VALUES ('2', '250', 'Standard Queen')
INSERT INTO RoomTypes (Room_Type_ID, Room_Cost, Room_Type)
VALUES ('3', '500', 'Deluxe Suite')

INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('1', '101')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('1', '102')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('1', '103')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('1', '104')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('1', '105')

INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('2', '106')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('2', '107')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('2', '108')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('2', '109')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('2', '110')

INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('3', '201')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('3', '202')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('3', '203')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('3', '204')
INSERT INTO Rooms (Room_Type_ID, Room_No)
VALUES ('3', '205')

SELECT * FROM RoomTypes
SELECT * FROM Rooms